### ISSUE TITLE
CPU Usage on connect

### ISSUE THREAD

**Issue by Slacquer** [LiveOrDevTrying/WebsocketsSimple#2]
Hello, love the project, however upon creating a very simple implementation, when a client connects (not listening to event, not sending and data etc, literally just connected and nothing else) the cpu usage is quite high.
After looking at the code, code you please add the following to your next version

await Task.Delay(1);  In the WebsocketsSimple.Server-> Handlers -> WebsocketHandler.StartReceivingMessagesAsync just after the line while (connection.Client.Connected)

I did this locally and all was perfectly fine, in fact I could then connect a few hundred clients without much of an issued.

**Comment by LiveOrDevTrying** [comment]
This is a great fix! Ty! I have updated the library and new packages are being built. Well done!
