### ISSUE TITLE
Websocket client - support URI containing a path

### ISSUE THREAD

**Issue by rdewaele** [LiveOrDevTrying/WebsocketsSimple#3]
I was considering this library for my use-case, but my connection URI contains a path (see https://datatracker.ietf.org/doc/html/rfc6455#section-3), which does not seem to be supported by this library.

Looking at https://github.com/LiveOrDevTrying/WebsocketsSimple/blob/master/WebsocketsSimple.Client/WebsocketClient.cs#L61-L63 the connection URI is always constructed from basic parts, with no support for a path.

Is this by design or are you open to supporting this use-case?
Maybe I am missing something?

EDIT: I should also mention that for my use-case the OAuth2 access token is passed as a query parameter.

**Comment by LiveOrDevTrying** [comment]
Good feedback. I will add in a a parameter for the path and make a commit. Ty for feedback :)

**Comment by LiveOrDevTrying** [comment]
Hi @rdewaele , This change has been commit and packages are building right now. Please take a look and if you run into any other issues, let me know. Thanks for using WebsocketsSimple!
