### ISSUE TITLE
Question: frameworks and cryptography algorithms supported?

### ISSUE THREAD

**Issue by fverdou** [LiveOrDevTrying/WebsocketsSimple#5]
So we have a .net standard 2.0 based Xamarin app, unknown server type for the time being, and want to be able to use ed25515 to sign certificates. Is this library a good candidate?

**Comment by LiveOrDevTrying** [comment]
Hello, apologies for the late reply. ED25515 is for private public key signing. WebsocketsSimple passes tokens (string) and they are managed in an IUserManager interface - the actual implementation is up to the programmer. You could base64 encode your certs, pass them as a token, and use ED25515 to verify signed tokens in your UserManager implementation. So I think yes this would be a good library for this.
