### ISSUE TITLE
Error Event: Length cannot be less than zero. (Parameter 'length')

### ISSUE THREAD

**Issue by tomvdb** [LiveOrDevTrying/WebsocketsSimple#6]
I'm trying to to a simple websocket server and have some javascript from a website connect to it. Server starts fine, but when the client tries to connect then I get a WsServer_ErrorEvent triggered with the message:

`Error Event: Length cannot be less than zero. (Parameter 'length')`

This is my ws server setup:

```
wsServer = new WebsocketServer(new ParamsWSServer(port : 8089, pingIntervalSec : 30 ));
wsServer.MessageEvent += WsServer_MessageEvent;
wsServer.ConnectionEvent += WsServer_ConnectionEvent;
wsServer.ErrorEvent += WsServer_ErrorEvent;
wsServer.ServerEvent += WsServer_ServerEvent;
wsServer.Start();

```

This is my javascript code for connection:

```
function connectWebsocket()
{
    console.log("Connecting to WS Server");
    sockurl = "ws://" + "127.0.0.1:8089";
    websocket = new WebSocket(sockurl);

    websocket.onopen = function () {
        console.log("Websocket Connected");
    };
    
    websocket.onerror = function () {
        console.log("Websocket Error");
    };
    
    websocket.onclose = function () {
        console.log("Websocket Closed");
    };
    
    websocket.onmessage = function (message) 
    {
        console.log(message);
    }
        
}
```

Server starts fine, and I get the error event when my client tries to connect. Am I missing an important settings?

Thanks!

**Comment by cameronwmckay** [comment]
I had the same problem, the solution I used was to use a "channel" on the web socket address.  So in your example above, if you can, change the address in this code and the javascript to be:

`sockurl = "ws://" + "127.0.0.1:8089/ws";`

**Comment by LiveOrDevTrying** [comment]
Hello and thank you for using WebsocketsSimple! I have fixed this bug and tested successfully with your client. The code is commit and new packages are available. Please give it a try and let me know if you have any other problems, questions, or suggestions for improvements. Thanks again for using WebsocketsSimple!
