### ISSUE TITLE
client returns error code 1006

### ISSUE THREAD

**Issue by 975269528** [LiveOrDevTrying/WebsocketsSimple#7]
![QQ图片20230420184720](https://user-images.githubusercontent.com/69647275/233346379-97e8bbb1-3103-40ea-8fe2-c05044dd5df7.png)

 As shown in the figure, after starting the server, an error message like this will be output when the client connects, and the client returns error code 1006. May I know where did I make a mistake? Thank you!

**Comment by LiveOrDevTrying** [comment]
Hello and thank you for using WebsocketsSimple.

This is a great find - this is happening because the "ConnectionSuccessString" is null. I will issue a fix and post here as soon as the packages are built.

**Comment by LiveOrDevTrying** [comment]
This has been fixed and new packages are available. Please let me know if you have any other issues, questions, or suggestions for improvements. Thank you for using WebsocketsSimple!
